language: node_js
node_js:
    - "lts/*"

cache:
    directories:
      - "node_modules"

stages:
    - lint
    - lint-styles
    - test
    - deploy

before_install:
    - npm ci

jobs:
    include:
      - stage: lint
        name: "Lint JS"
        script:
          - npm run lint
      - stage: lint-styles
        name: "Lint CSS"
        script:
          - npm run lint-styles
      - stage: test
        name: "Unit tests"
        script:
          - npm run test
      - stage: deploy
        name: "Deploy with Netlify"
        script:
          - export NODE_ENV=production
          - npm run build
          - cp netlify.toml build
          - npm i netlify-cli -g
          - netlify deploy --dir=build --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID --context production --message="CI/CD build" -p
        only:
          - master
