language: node_js
node_js:
    - "lts/*"

cache:
    directories:
      - "node_modules"

stages:
    - lint
    - lint-styles
    - test
    - name: build
      if: branch = master

before_install:
    - npm ci

jobs:
    include:
      - stage: lint
        name: "Lint JS"
        script:
          - npm run lint
      - stage: lint-styles
        name: "Lint CSS"
        script:
          - npm run lint-styles
      - stage: test
        name: "Unit tests"
        script:
          - npm run test
      - stage: build
        name: "Production build"
        script:
          - export NODE_ENV=production
          - npm run build
          - cp netlify.toml build
          deploy:
              provider: netlify
              dir: "./build"
              site: $NETLIFY_SITE_ID
              auth: $NETLIFY_AUTH_TOKEN
              prod: true
              message: "CI/CD build"
              on:
                branch: master
              edge: true
